### ISSUE TITLE
卡刷包错误1

### ISSUE THREAD

**Issue by Fyg369** [dabao1955/kernel_build_action#1]
我改了action.yml里面如下图的位置，仿佛没生效一样。
![mmexport1698327379776](https://github.com/dabao1955/kernel_build_action/assets/142138034/33464d43-d445-484e-81e4-f45ee5a06426)
![mmexport1698327382873](https://github.com/dabao1955/kernel_build_action/assets/142138034/548cbfc0-60de-49af-a549-8bab15d4e5e2)
![e8386f2b1242a6e9998421e55105ed05](https://github.com/dabao1955/kernel_build_action/assets/142138034/8bbc6f0a-8227-4193-aad6-18b12bab131a)

**Comment by dabao1955** [comment]
[此版本](https://github.com/dabao1955/kernel_build_action/tree/10e4899324ff4717a45c7d11668986adecdf27f4)可能会解决此问题？

**Comment by Fyg369** [comment]
> [此版本](https://github.com/dabao1955/kernel_build_action/tree/10e4899324ff4717a45c7d11668986adecdf27f4)可能能解决此问题吗？

感谢修改，只是不明白我Fork了大佬的仓库，修改无效不知道什么问题导致。

**Comment by dabao1955** [comment]
> > [此版本](https://github.com/dabao1955/kernel_build_action/tree/10e4899324ff4717a45c7d11668986adecdf27f4)可能能解决此问题吗？
> 
> 感谢修改，只是不明白我Fork了大佬的仓库，修改无效不知道什么问题导致。

~~啊这，其实可以不用fork的~~

**Comment by Fyg369** [comment]
> > > [此版本](https://github.com/dabao1955/kernel_build_action/tree/10e4899324ff4717a45c7d11668986adecdf27f4)可能能解决此问题吗？
> > 
> > 
> > 感谢修改，只是不明白我Fork了大佬的仓库，修改无效不知道什么问题导致。
> 
> ~啊这，其实可以不用fork的~

啊这，习惯了fork。。。。。。

**Comment by Fyg369** [comment]
经过测试还是卡刷包错误，这个地方始终不能自动。原作者路径是这个
 sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
![Screenshot_20231026-224320](https://github.com/dabao1955/kernel_build_action/assets/142138034/58dfefbb-c49f-4c22-bec5-fa161a40788f)

**Comment by dabao1955** [comment]
> 经过测试还是卡刷包错误，这个地方始终不能自动。原作者路径是这个 sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh ![Screenshot_20231026-224320](https://user-images.githubusercontent.com/142138034/278382149-58dfefbb-c49f-4c22-bec5-fa161a40788f.jpg)

已修复 539e2ba

**Comment by Fyg369** [comment]
> > 经过测试还是卡刷包错误，这个地方始终不能自动。原作者路径是这个 sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh ![Screenshot_20231026-224320](https://user-images.githubusercontent.com/142138034/278382149-58dfefbb-c49f-4c22-bec5-fa161a40788f.jpg)
> 
> 已修复 [539e2ba](https://github.com/dabao1955/kernel_build_action/commit/539e2bac18c3ebc0c732fb622afa75327430cb09)

感谢修复，能添加Kali-Nethunter支持选项就好了

**Comment by dabao1955** [comment]
> > > 经过测试还是卡刷包错误，这个地方始终不能自动。原作者路径是这个 sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh ![Screenshot_20231026-224320](https://user-images.githubusercontent.com/142138034/278382149-58dfefbb-c49f-4c22-bec5-fa161a40788f.jpg)
> > 
> > 
> > 已修复 [539e2ba](https://github.com/dabao1955/kernel_build_action/commit/539e2bac18c3ebc0c732fb622afa75327430cb09)
> 
> 感谢修复，能添加Kali-Nethunter支持选项就好了

会考虑的

**Comment by Fyg369** [comment]
大佬能否考虑添加第三方的clang构建工具

**Comment by dabao1955** [comment]
> 大佬能否考虑添加第三方的clang构建工具

会考虑的

**Comment by Fyg369** [comment]
> > 大佬能否考虑添加第三方的clang构建工具
> 
> 会考虑的

感谢考虑

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/f3e8953e-ca11-4b0a-9e1a-d4150bb80526)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/d25c161a-f54a-49a7-bb23-736c2cc4b207)
![3](https://github.com/dabao1955/kernel_build_action/assets/142138034/dec08c66-324
![4](https://github.com/dabao1955/kernel_build_action/assets/142138034/00365712-9d63-4a2b-abf0-8b759be587ad)
2-4c6c-99cf-a3dc6a5c42e0)

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/6a02fb49-9209-4b28-a476-0ee985a32ebf)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/fec49c58-3e81-4e2e-9cb2-6dc45ec8c491)
![3](https://github.com/dabao1955/kernel_build_action/assets/142138034/535ef0e1-db29-4508-a602-dacb870a805a)
![4](https://github.com/dabao1955/kernel_build_action/assets/142138034/b42f92f4-16fc-457d-8cca-67ff547e4052)

**Comment by Fyg369** [comment]
不Fork大佬的仓库，自己建立仓库构建内核出现：设备上没有剩余空间
Fork大佬的仓库构建内核出现gcc: 找不到命令和编译器不支持 -fstack-protector-strong
配置在第三张图里

**Comment by Fyg369** [comment]
不Fork大佬的仓库，自己建立的仓库构建内核出现：设备上没有剩余空间
Fork大佬的仓库构建内核出现gcc: 找不到命令和编译器不支持-fstack-protector-strong
配置在第三张图里

**Comment by Fyg369** [comment]
不Fork大佬的仓库，自己建立的仓库构建内核出现：设备上没有剩余空间
Fork大佬的仓库构建内核出现gcc: 找不到命令和编译器不支持-fstack-protector-strong
配置在第三张图里

**Comment by Fyg369** [comment]
![5](https://github.com/dabao1955/kernel_build_action/assets/142138034/3e34cb25-ecf1-412a-bed2-9ae5ede2179a)

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/c063e649-8a8f-4fbb-86e2-1406bb37616e)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/2be6cf34-4e92-4bff-a11d-86775f7b703e)
![3](https://github.com/dabao1955/kernel_build_action/assets/142138034/39e06d4a-a133-4996-ac6d-11c887c958b4)

**Comment by Fyg369** [comment]
设备空间不够问题我已经解决了，使用第三方构建工具貌似大佬没有写全，缺少了export和make这部分。

**Comment by dabao1955** [comment]
> 设备空间不够问题我已经解决了，使用第三方构建工具貌似大佬没有写全，缺少了export和make这部分。

已修复 a95b4b7
~~另外最好重新开一个issue省的我看不到~~

**Comment by dabao1955** [comment]
> ![5](https://user-images.githubusercontent.com/142138034/284137873-3e34cb25-ecf1-412a-bed2-9ae5ede2179a.png)

第三方clang与aosp-clang冲突;

**Comment by dabao1955** [comment]
> ![1](https://user-images.githubusercontent.com/142138034/284133953-6a02fb49-9209-4b28-a476-0ee985a32ebf.png) ![2](https://user-images.githubusercontent.com/142138034/284133985-fec49c58-3e81-4e2e-9cb2-6dc45ec8c491.png) ![3](https://user-images.githubusercontent.com/142138034/284133999-535ef0e1-db29-4508-a602-dacb870a805a.png) ![4](https://user-images.githubusercontent.com/142138034/284134015-b42f92f4-16fc-457d-8cca-67ff547e4052.jpg)

没遇到过诶(
![Screenshot_2023-11-20-17-33-08-08_df198e732186825c8df26e3c5a10d7cd](https://github.com/dabao1955/kernel_build_action/assets/79307765/6786cf81-dc7f-44a5-9502-bcd180e35854)

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/7dd56c4c-1416-40b5-b44e-17a25c8644c0)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/9146427e-7cfa-4b9c-8d61-015020580464)

**Comment by Fyg369** [comment]
刚使用了更新的action.yml，貌似运行时只能使用GCC构建内核，使用不到第三方Clang构建内核。

**Comment by dabao1955** [comment]
> 刚使用了更新的action.yml，貌似运行时只能使用GCC构建内核，使用不到第三方Clang构建内核。

aosp-gcc打开了吗？

**Comment by Fyg369** [comment]
> > 刚使用了更新的action.yml，貌似运行时只能使用GCC构建内核，使用不到第三方Clang构建内核。
> 
> aosp-gcc打开了吗？

打开了

**Comment by Fyg369** [comment]
![6](https://github.com/dabao1955/kernel_build_action/assets/142138034/614afe89-7bb4-425b-834f-3c4946a24503)

**Comment by dabao1955** [comment]
> > > 刚使用了更新的action.yml，貌似运行时只能使用GCC构建内核，使用不到第三方Clang构建内核。
> > 
> > 
> > aosp-gcc打开了吗？
> 
> 打开了
估计是脚本的优先级搞错了，正在排查

**Comment by Fyg369** [comment]
正在尝试aosp-gcc: false 和aosp-clang: false

**Comment by dabao1955** [comment]
已修复8c34b27
把aosp-gcc优先级扔最后了
虽然不是最优解

**Comment by Fyg369** [comment]
> 已修复 [8c34b27](https://github.com/dabao1955/kernel_build_action/commit/8c34b271cc943883c2b3d7818e62c1e7c8b1f8bc) 把aosp-gcc优先级扔最后了 虽然不是最优解

好 我试试  请问ccache: true只能开启Clang才有效果吗？同时开启GCC也有效果吗？

**Comment by Fyg369** [comment]
sudo fallocate -l 16G $SWAP_FILE这里我只能设置12G，多了就会出现设备没有剩余空间，不知道是什么原因导致

**Comment by dabao1955** [comment]
> > 已修复 [8c34b27](https://github.com/dabao1955/kernel_build_action/commit/8c34b271cc943883c2b3d7818e62c1e7c8b1f8bc) 把aosp-gcc优先级扔最后了 虽然不是最优解
> 
> 好 我试试 请问ccache: true只能开启Clang才有效果吗？同时开启GCC也有效果吗？

没效果(

**Comment by dabao1955** [comment]
> sudo fallocate -l 16G $SWAP_FILE这里我只能设置12G，多了就会出现设备没有剩余空间，不知道是什么原因导致

嘶，这个我也不知道为什么
