### ISSUE TITLE
[feature]: 使用自定义AnyKernel3

### ISSUE THREAD

**Issue by ztc1997** [dabao1955/kernel_build_action#12]
### Describe the solution you'd like

有时候我们希望在安装内核时进行安装附加模块等操作，能否提供一个选项，允许使用自定义的AnyKernel3

**Comment by dabao1955** [comment]
这个会考虑的，不过一般情况下什么时候需要自定义Anykernel3呢？

**Comment by ztc1997** [comment]
> 这个会考虑的，不过一般情况下什么时候需要自定义Anykernel3呢？

比如安装附加模块，检查机型，检查当前内核是否内置ksu

**Comment by dabao1955** [comment]
> > 这个会考虑的，不过一般情况下什么时候需要自定义Anykernel3呢？
> 
> 比如安装附加模块，检查机型，检查当前内核是否内置ksu

try https://github.com/dabao1955/kernel_build_action/tree/squash-conf
