### ISSUE TITLE
请求添加设置dtc功能[feature]: 

### ISSUE THREAD

**Issue by Fyg369** [dabao1955/kernel_build_action#14]
### Describe the solution you'd like

有些内核源码编译需要设置dtc和导入dtc才能编译成功
![Screenshot_20240505-080621](https://github.com/dabao1955/kernel_build_action/assets/142138034/34c5e5a1-d9b0-44e9-9a76-db76317c8702)

**Comment by Fyg369** [comment]
还有一个下载内核源代码 [!] 警告：请使用 --recursive 进行克隆！这个麻烦大佬有时间也添加一下   谢谢

**Comment by dabao1955** [comment]
1.不添加dtc能构建成功吗？
2.我觉得这个没太大意义，本身克隆源码时就会克隆子模块

**Comment by Fyg369** [comment]
> 1.不添加dtc构建成功吗？ 2.我觉得这个克隆意义不大，本身克隆源码时就会子模块

不添加dtc构建编译会报错

**Comment by dabao1955** [comment]
> > 1.不添加dtc构建成功吗？ 2.我觉得这个克隆意义不大，本身克隆源码时就会子模块
> 
> 不添加dtc构建编译会报错

有没有具体日志？

**Comment by Fyg369** [comment]
> > > 1.不添加dtc构建成功吗？ 2.我觉得这个克隆意义不大，本身克隆源码时就会子模块
> > 
> > 
> > 不添加dtc构建编译会报错
> 
> 有没有具体日志？

https://github.com/Fyg369/Kernel-Action/actions/runs/8964541712/job/24616457062

**Comment by dabao1955** [comment]
try:
```
        uses: dabao1955/kernel_build_action@main
        with:
          extra-cmd: DTC_EXT=dtc/dtc
```

**Comment by Fyg369** [comment]
> 尝试：
> 
> ```
>         uses: dabao1955/kernel_build_action@main
>         with:
>           extra-cmd: DTC_EXT=dtc/dtc
> ```

大佬没看到你提供的最新修改在什么地方

**Comment by dabao1955** [comment]
什么修改
要使用dtc的话在工作流文件里添加一行 extra-cmd: DTC=dtc/dtc 就行

**Comment by Fyg369** [comment]
> 什么修改 要使用dtc的话在工作流文件里添加一行 extra-cmd: DTC=dtc/dtc 就行

好的感谢我试试

**Comment by Fyg369** [comment]
还是编译错误了https://github.com/Grill-Laux/OOS_kernel_oneplus_sdm845这是我编译的内核源码，里面提供的编译教程有说到dtc和编译工具

**Comment by dabao1955** [comment]
> 还是编译错误了，这是我编译的内核源码，里面提供的编译教程有说到dtc和编译工具
> 
> https://github.com/Grill-Laux/OOS_kernel_oneplus_sdm845

  /bin/sh: 1: dtc/dtc: not found
  make[3]: *** [scripts/Makefile.lib:319: arch/arm64/boot/dts/qcom/sdm845-v2.1.dtb] Error 127

我觉得应该检查一下dtc的路径 DTC_EXT=$(pwd)/dtc/dtc

**Comment by Fyg369** [comment]
> > 还是编译错误了，这是我编译的内核源码，里面提供的编译教程有说到dtc和编译工具
> > https://github.com/Grill-Laux/OOS_kernel_oneplus_sdm845
> 
> /bin/sh: 1: dtc/dtc: not found make[3]: *** [scripts/Makefile.lib:319: arch/arm64/boot/dts/qcom/sdm845-v2.1.dtb] Error 127
> 
> 我觉得应该检查一下dtc的路径 DTC_EXT=$(pwd)/dtc/dtc

谢谢我再试试

**Comment by Fyg369** [comment]
DTC     arch/arm64/boot/dts/qcom/sdm845-v2.1.dtb
  CC      lib/assoc_array.o
/bin/sh: 1: /home/runner/work/Kernel-Action/Kernel-Action/kernel/mb/dtc/dtc: Permission denied
编译错误提示
make[3]: *** [scripts/Makefile.lib:319: arch/arm64/boot/dts/qcom/sdm845-v2.1.dtb] Error 126
make[2]: *** [../scripts/Makefile.build:653: arch/arm64/boot/dts/qcom] Error 2
make[1]: *** [arch/arm64/Makefile:161: dtbs] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      lib/bitrev.o

![Screenshot_20240510-133114](https://github.com/dabao1955/kernel_build_action/assets/142138034/3cf2e465-3d15-4737-a116-7eb9ea6e894b)

**Comment by dabao1955** [comment]
> DTC arch/arm64/boot/dts/qcom/sdm845-v2.1.dtb CC lib/assoc_array.o /bin/sh: 1: /home/runner/work/Kernel-Action/Kernel-Action/kernel/mb/dtc/dtc: Permission denied 编译错误提示 make[3]: *** [scripts/Makefile.lib:319: arch/arm64/boot/dts/qcom/sdm845-v2.1.dtb] Error 126 make[2]: *** [../scripts/Makefile.build:653: arch/arm64/boot/dts/qcom] Error 2 make[1]: *** [arch/arm64/Makefile:161: dtbs] Error 2 make[1]: *** Waiting for unfinished jobs.... CC lib/bitrev.o
> 
> ![Screenshot_20240510-133114](https://private-user-images.githubusercontent.com/142138034/329470082-3cf2e465-3d15-4737-a116-7eb9ea6e894b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzY2NzIsIm5iZiI6MTcxNTMzNjM3MiwicGF0aCI6Ii8xNDIxMzgwMzQvMzI5NDcwMDgyLTNjZjJlNDY1LTNkMTUtNDczNy1hMTE2LTdlYjllYTZlODk0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDE5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDEzNjdlMTdlNjFkMTI3NWQ3NTI4ZDRmMmEzYjhiNjdkNWJhZGEyZjEzMGU5YzcwOGZkNzdhMzhkYzQxNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FSYwkwXgxfruvNbwuV98lvowibHuhKRLlHrO16fs6cg)

https://zhuanlan.zhihu.com/p/688044072
