### ISSUE TITLE
[Bug]: 内核刷入路径错误

### ISSUE THREAD

**Issue by Fyj69** [dabao1955/kernel_build_action#18]
### CheckBox

- [X] I have searched the issue list and found no similar issues.
- [X] I use the official action instead of someone else's
- [X] I have read the FAQ section in README.md

### Configuration

uses: dabao1955/kernel_build_action@main
with:
  xxx: xxx

### Describe the bug

编译成功内核刷新出现路径错误无法刷入

### Screenshots

![Screenshot_20240513-173029](https://github.com/dabao1955/kernel_build_action/assets/18164452/5c61776c-9e37-4825-bc5d-d08e5ddee1c1)

**Comment by Fyj69** [comment]
无法确定/dev/block/platform/omap/omap_hsmmc.0/by-name/boot分区的。正在终止。

**Comment by dabao1955** [comment]
anykernel.sh发过来看看

**Comment by dabao1955** [comment]
![Screenshot_2024-05-13-23-12-54-68_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/dabao1955/kernel_build_action/assets/79307765/bfae2640-0a5a-45ed-ba77-f87ce080b99d)

~~从ci下下来的Anykernel3没有任何问题的~~

**Comment by Fyj69** [comment]
> ![Screenshot_2024-05-13-23-12-54-68_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/79307765/330110596-bfae2640-0a5a-45ed-ba77-f87ce080b99d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTU3NTcsIm5iZiI6MTcxNTY1NTQ1NywicGF0aCI6Ii83OTMwNzc2NS8zMzAxMTA1OTYtYmZhZTI2NDAtMGE1YS00NWVkLWJhNzctZjg3Y2UwODBiOTlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyNTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZTc3ODFhNmJiZTliZTBhYWVhNjRiYWMwMjNiNzU5MmViNzdhMTUxNDAwNWNiZDZhNTFkMzMxMjUyYjc1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nw2S0-ob-Lyxl3siHsSO4wcFlnDI4LUa7l_8x1QjbtI)
> 
> ~从ci下下来的Anykernel3没有任何问题的~

之前是可以刷入的，不知道现在什么原因导致无法刷入，我用Kernel Flasher工具备份了boot.img，在通过Android Image Kitchen工具解包了boot.img，之后替换了编译成功的Image.gz-dtb内核文件，再用Android Image Kitchen工具重新打包成新的boot.img才刷入成功。。。。。。

**Comment by dabao1955** [comment]
> > ![Screenshot_2024-05-13-23-12-54-68_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/79307765/330110596-bfae2640-0a5a-45ed-ba77-f87ce080b99d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTU3NTcsIm5iZiI6MTcxNTY1NTQ1NywicGF0aCI6Ii83OTMwNzc2NS8zMzAxMTA1OTYtYmZhZTI2NDAtMGE1YS00NWVkLWJhNzctZjg3Y2UwODBiOTlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyNTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZTc3ODFhNmJiZTliZTBhYWVhNjRiYWMwMjNiNzU5MmViNzdhMTUxNDAwNWNiZDZhNTFkMzMxMjUyYjc1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nw2S0-ob-Lyxl3siHsSO4wcFlnDI4LUa7l_8x1QjbtI)
> > ~从ci下下来的Anykernel3没有任何问题的~
> 
> 之前是可以刷入的，不知道现在什么原因导致无法刷入，我用Kernel Flasher工具备份了boot.img，在通过Android Image Kitchen工具解包了boot.img，之后替换了编译成功的Image.gz-dtb内核文件，再用Android Image Kitchen工具重新打包成新的boot.img才刷入成功。。。。。。

我用action试了一下复现不了
