### ISSUE TITLE
请求支持自定义克隆深度和克隆内核项目子模块

### ISSUE THREAD

**Issue by ClererQ** [dabao1955/kernel_build_action#2]

**Comment by dabao1955** [comment]
对于内核源码来说只克隆一层应该就够了吧

**Comment by ClererQ** [comment]
![Screenshot_2023-11-06-19-11-26-805_com.github.android.jpg](https://github.com/dabao1955/kernel_build_action/assets/140988459/cdf4141a-03b0-4a92-b512-ef52b8443c2f)

比如这个会用到上一个commit

**Comment by dabao1955** [comment]
> ![Screenshot_2023-11-06-19-11-26-805_com.github.android.jpg](https://user-images.githubusercontent.com/140988459/280686687-cdf4141a-03b0-4a92-b512-ef52b8443c2f.jpg)
> 
> 比如这个会用到上一个commit

fixed eeb9963
