### ISSUE TITLE
[feature]: 关于kernelsu lkm驱动的编译添加

### ISSUE THREAD

**Issue by liaoke01** [dabao1955/kernel_build_action#21]
### Related problem

希望可以在kernelsu打开的前提下，可以选择直接将其编译进内核，以gki模式启动。或者选择单独将kernelsu编译成ko模块,然后在工作流中insmod kernel,上传加载了ko的kernel

### Describe the solution you'd like

.

**Comment by dabao1955** [comment]
kernelsu官方不是提供了lkm吗

**Comment by liaoke01** [comment]
> kernelsu官方不是提供了lkm吗

有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型

**Comment by liaoke01** [comment]
> kernelsu官方不是提供了lkm吗

关于lkm模式的配置,可以看一下我的工作流，https://github.com/liaoke01/kernelsu-lkm-for-unofficial-kernel-build/blob/main/.github/workflows/main.yml

**Comment by dabao1955** [comment]
> > kernelsu官方不是提供了lkm吗
> 
> 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型

https://github.com/xiaoleGun/KernelSU_Action/issues/150
https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652

综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。

**Comment by liaoke01** [comment]
> > > kernelsu官方不是提供了lkm吗
> > 
> > 
> > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> 
> [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> 
> 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。

非gki设备也可使用ko内核模块,没有必要添加检测

**Comment by liaoke01** [comment]
> > > kernelsu官方不是提供了lkm吗
> > 
> > 
> > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> 
> [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> 
> 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。

不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本

**Comment by dabao1955** [comment]
> > > > kernelsu官方不是提供了lkm吗
> > > 
> > > 
> > > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> > 
> > 
> > [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> > 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。
> 
> 不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本

有成功的例子吗

**Comment by dabao1955** [comment]
> > > > kernelsu官方不是提供了lkm吗
> > > 
> > > 
> > > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> > 
> > 
> > [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> > 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。
> 
> 不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本

这个已经有了

**Comment by liaoke01** [comment]
> > > kernelsu官方不是提供了lkm吗
> > 
> > 
> > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> 
> [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> 
> 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。

不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本

> > > > > kernelsu官方不是提供了lkm吗
> > > > 
> > > > 
> > > > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> > > 
> > > 
> > > [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> > > 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。
> > 
> > 
> > 不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本
> 
> 有成功的例子吗

有,不保证全部可用,但是有 非gki 使用ko成功的例子,具体能不能用交给用户自己判断,在readme里面说明一下就行了

**Comment by dabao1955** [comment]
> > > > kernelsu官方不是提供了lkm吗
> > > 
> > > 
> > > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> > 
> > [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> > 
> > 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。
> 
> 不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本
> 
> > > > > > kernelsu官方不是提供了lkm吗
> > > > > 
> > > > > 
> > > > > 有些特殊的机型，可能会有一些错误,用自己的开源内核代码构建出来更好,以及适用于一些非gki机型
> > > > 
> > > > 
> > > > [xiaoleGun/KernelSU_Action#150](https://github.com/xiaoleGun/KernelSU_Action/issues/150) [#9 (comment)](https://github.com/dabao1955/kernel_build_action/issues/9#issuecomment-2011815652)
> > > > 综上所述我会考虑开启选项后进行内核版本检测，非gki将不会构建。
> > > 
> > > 
> > > 不过需要注意的是,最新版本的kernelsu已经删除的对非gki内核支持的代码,不清楚是否还可以编译出ko模块,不行的话可以添加一个检测到非gki内核，强制使用最后一个受支持的kernelsu版本
> > 
> > 有成功的例子吗
> 
> 有,不保证全部可用,但是有 非gki 使用ko成功的例子,具体能不能用交给用户自己判断,在readme里面说明一下就行了
好的
