### ISSUE TITLE
[Bug]: arch/arm64/Makefile:47: *** CROSS_COMPILE_ARM32 not defined or empty, the compat vDSO will not be built.  Stop.

### ISSUE THREAD

**Issue by Eric-Du-BH** [dabao1955/kernel_build_action#27]
### CheckBox

- [X] I have searched the issue list and found no similar issues.
- [X] I use the official action instead of someone else's
- [X] I have read the FAQ section in README.md

### Configuration

name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/PixelExperience-Devices/kernel_oneplus_msm8998
          kernel-branch: eleven
          config: lineage_oneplus5_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r365631c

### Describe the bug

I get an error when compiling the kernel

### Error Logs

arch/arm64/Makefile:47: *** CROSS_COMPILE_ARM32 not defined or empty, the compat vDSO will not be built.  Stop.

**Comment by dabao1955** [comment]
May fixed on 6970acc6114ebdd068edf5c8415a56d956766e9b
