### ISSUE TITLE
使用第三方clang编辑器编译失败

### ISSUE THREAD

**Issue by dabao1955** [dabao1955/kernel_build_action#3]

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/30097255-0e73-4dff-bbb3-a3d2fb26d384)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/c09207c4-1d3a-44e0-b123-f3d7dca6d982)
![3](https://github.com/dabao1955/kernel_build_action/assets/142138034/08b67898-2464-4cc9-87c8-9b5076fa5dc1)

**Comment by Fyg369** [comment]
感谢修复，终于成功了

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/6771ca3a-3f9a-4415-bc4f-31abeb4d51c6)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/92710477-f1b5-4305-b280-15ec47190bb1)
大佬这是啥我问题，我就添加了这段代码，内核路径也没错啊！编译的时候就会出现如上图路径错误
跑到了/home/runner/work/_temp/这个路径，有时间请大佬给指点下 谢谢

**Comment by Fyg369** [comment]
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/ed620c90-125d-435e-bff2-1a9a4f2df896)
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/e8aee19c-b838-43f6-a222-84f0e7b2d417)
如上图添加的代码，路径应该没问题，但在编译时却遇到如上图路径错误，不知道什么原因会导致编译时路径跑到/home/runner/work/_temp/下，大佬有时间还请指导下 谢谢

**Comment by dabao1955** [comment]
不好意思，没有接触过，我研究看一下
________________________________
