### ISSUE TITLE
[Bug]: nethunter补丁问题

### ISSUE THREAD

**Issue by Fyg369** [dabao1955/kernel_build_action#36]
### CheckBox

- [X] I have searched the issue list and found no similar issues.
- [X] I use the official action instead of someone else's
- [X] I have read the FAQ section in README.md

### Configuration

uses: dabao1955/kernel_build_action@main
with:
  xxx: xxx

### Describe the bug

我的内核版本是4.9，目前add-wifi-injection-4.14.patch补丁，在编译时被判断为不打补丁，没有被编译进去，请大佬看下是什么问题导致
![3](https://github.com/user-attachments/assets/ce963e6d-3235-4ba9-8cf2-538eaaf300af)

### Screenshots

![1](https://github.com/user-attachments/assets/494e1a00-9f1a-4a3c-a25e-55ac97d7356f)
![2](https://github.com/user-attachments/assets/a343ac7f-40b2-4cd8-a5c9-db47e8252e2e)

**Comment by dabao1955** [comment]
log pls

**Comment by Fyg369** [comment]
> log pls

已解决
![3](https://github.com/user-attachments/assets/7aab5e33-1b65-4a09-bc8f-0641eb77cb35)

**Comment by dabao1955** [comment]
> 我删除了和修改了关于SUBLEVEL几处代码现在没问题了 ![1](https://private-user-images.githubusercontent.com/142138034/372357417-fda45a23-acbc-4ffc-8518-1b44fdf9ac5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzMzNTEsIm5iZiI6MTcyNzc3MzA1MSwicGF0aCI6Ii8xNDIxMzgwMzQvMzcyMzU3NDE3LWZkYTQ1YTIzLWFjYmMtNGZmYy04NTE4LTFiNDRmZGY5YWM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwODU3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQzZTliZGJlNGY4MjhlZWQwMWQ1NjA0YzE0MjlhZjJiYTA2ZTc0MDRkYjFjNWMzODljYTU2YTEyNTgxYjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gxfR8lTW-oy65mRmbPDwGDNuOvHaw-Q6WOUYcB5adpQ) ![2](https://private-user-images.githubusercontent.com/142138034/372357432-975c0a9a-3131-42ae-b5c1-d03eca5e1e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzMzNTEsIm5iZiI6MTcyNzc3MzA1MSwicGF0aCI6Ii8xNDIxMzgwMzQvMzcyMzU3NDMyLTk3NWMwYTlhLTMxMzEtNDJhZS1iNWMxLWQwM2VjYTVlMWUyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwODU3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODkyOWU5YjgyOGE2MzcxYjUzZjA5Yjg4MTY1YjFjMjBhMDg0NDg5Njk5N2YxYmJjZDdhNjIyOTk5ZTIxM2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g3pmSolJqBG_Zwkrpm0wdSpemwJd9wD9JVHlPnURKPA) ![4](https://private-user-images.githubusercontent.com/142138034/372357952-e0d28019-81b7-4af7-aee5-b6493d8daac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzMzNTEsIm5iZiI6MTcyNzc3MzA1MSwicGF0aCI6Ii8xNDIxMzgwMzQvMzcyMzU3OTUyLWUwZDI4MDE5LTgxYjctNGFmNy1hZWU1LWI2NDkzZDhkYWFjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwODU3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDAyNDBmYmZhZDRjY2Q5MzM0MTRlN2M3MDQ1OTgxZGY0YmZlN2M2ZmYwODIyZWY5YTE4YjdjM2FlYTU0MTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pQS0gio4Z2cro7tjJTfv6ejcf0P9Ri1T2jgtBAU-IMo)
> 
> 这里多了两个SUBLEVEL ![3](https://private-user-images.githubusercontent.com/142138034/372357904-54d3caa4-4707-42a6-80af-762158d33412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NzMzNTEsIm5iZiI6MTcyNzc3MzA1MSwicGF0aCI6Ii8xNDIxMzgwMzQvMzcyMzU3OTA0LTU0ZDNjYWE0LTQ3MDctNDJhNi04MGFmLTc2MjE1OGQzMzQxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwODU3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmU4YWI4ZjFjMzcxZWZjYzc4NTIwNTAwMTIzYWEwNDExZDY4MGY4YzAxYjQwZDAwYjZhYTFiZjcxM2U5YjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oN5HsopVfw0jW_dKv1iZEr6eXT4mcJ7NPKPEqYmse6k)

不知道，这段我是从ksu上面的ci上抄过来的

**Comment by Fyg369** [comment]
经过测试第三方编译工具链问题可能是编译命令导致，如下图用第三方编译工具少了一个CC=clang命令
![Screenshot_20241021-132338](https://github.com/user-attachments/assets/051073e8-c4e5-4251-9cf2-d73c896272ba)
![Screenshot_20241021-132125](https://github.com/user-attachments/assets/05e11089-acfe-49fb-b132-9642b84ba95f)
![Screenshot_20241021-132023](https://github.com/user-attachments/assets/66506e5f-fe15-45dc-a211-608bda4f340c)

**Comment by Fyg369** [comment]
感觉这里的编译命令代码要修改一下
echo "::group:: Building Kernel with selected cross compiler"
         mkdir out -p -v
         COMMAND="make -j$(nproc --all) ${{ inputs.config }} ARCH=${{ inputs.arch }} all ${{ inputs.extra-cmd }} O=out"
         if [ ${{ inputs.aosp-clang }} = true ] || [ ${{ inputs.android-ndk }} = false ]; then
              COMMAND+=" PATH=$HOME/clang/bin:$PATH"
         elif [ ${{ inputs.android-ndk }} = true ]; then
              COMMAND+=" CLANG_PATH=$HOME/android-ndk-${{ inputs.android-ndk-version }}/toolchains/llvm/prebuilt/linux-x86_64"
         fi
         export PATH=$CLANG_PATH/bin:$PATH
         if [ ${{ inputs.aosp-gcc }} = true ]; then
             COMMAND+=" CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- CROSS_COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu-"
         elif [ ${{ inputs.android-ndk }} = true ]; then
             COMMAND+=" CROSS_COMPILE=$CLANG_PATH/bin/llvm- CROSS_COMPILE_ARM32=$CLANG_PATH/bin/llvm-"
         fi
         if [ ${{ inputs.aosp-clang }} = true ] || [ ${{ inputs.android-ndk }} = true ]; then
             if [ ${{ inputs.ccache }} = true ]; then
                 COMMAND+=" CC='ccache clang'"
             else
                 COMMAND+=" CC=clang"
             fi
         else
             if [ ${{ inputs.ccache }} = true ]; then
                 COMMAND+=" CC='ccache $HOME/gcc-64/bin/aarch64-linux-android-gcc'"
             fi
         fi
         echo "using command: ${COMMAND}"
         ${COMMAND}
         echo "::endgroup::"

         unset USE_CCACHE CLANG_TRIPLE CROSS_COMPILE_ARM32 CROSS_COMPILE CLANG_PATH HOMES SUBLEVEL KVER COMMAND SWAP_FILE SUBLEVEL PATCHLEVEL VERSION
