### ISSUE TITLE
Third party GCC Support

### ISSUE THREAD

**Issue by dabao1955** [dabao1955/kernel_build_action#39]

**Comment by Fyg369** [comment]
这里我之前改过其它gcc添加后面的代码可以正常编译内核成功

![1](https://github.com/user-attachments/assets/4a8eda7b-9ecd-49f5-8a87-715a7bcc6f80)

![2](https://github.com/user-attachments/assets/32d9b8af-8e45-4f58-8f01-5cbd6b91c331)

**Comment by Fyg369** [comment]
> 这里我之前修改过其他gcc添加后面的代码可以正常编译内核成功
> 
> ![1](https://private-user-images.githubusercontent.com/142138034/384684924-4a8eda7b-9ecd-49f5-8a87-715a7bcc6f80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzkxNTgsIm5iZiI6MTczMTIzODg1OCwicGF0aCI6Ii8xNDIxMzgwMzQvMzg0Njg0OTI0LTRhOGVkYTdiLTllY2QtNDlmNS04YTg3LTcxNWE3YmNjNmY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMTQwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDBmYjlmNjA4NDYyYzdjNDkxMGY3MGJiYTExMDNmOGZiZDRmOTY3MTVlZDFkOTMyMzljYTA2MjgyMjhmNGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8R3NTSRB47vLdGaLuCKJJgMmMK1TqHNBRQoqpJhvqqc)
> 
> ![2](https://private-user-images.githubusercontent.com/142138034/384684936-32d9b8af-8e45-4f58-8f01-5cbd6b91c331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzkxNTgsIm5iZiI6MTczMTIzODg1OCwicGF0aCI6Ii8xNDIxMzgwMzQvMzg0Njg0OTM2LTMyZDliOGFmLThlNDUtNGY1OC04ZjAxLTVjYmQ2YjkxYzMzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMTQwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWU5YmJmMWJhZGVmZTJhNWQ4NjU3NGI0ZWE1OGU3YzMyYjgwNDQ3YzI2ODg2YjI4YjI2NDdhZTNhZjAyODAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0QVZh0dwbBh-HlJeF6GMS859Fp02YPS4fQD9L_ky3g8)

后面添加这段代码可以减少编译上的错误
if [ ! -d $HOME/gcc-64/bin/ ] || [ ! -d $HOME/gcc-32/bin/ ]; then
                 [ ! -d $HOME/gcc-64/bin/ ] && mv $HOME/gcc-64/*/* $HOME/gcc-64/
                 [ ! -d $HOME/gcc-32/bin/ ] && mv $HOME/gcc-32/*/* $HOME/gcc-32/
             fi
