### ISSUE TITLE
ccache

### ISSUE THREAD

**Issue by Fyg369** [dabao1955/kernel_build_action#4]
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/4469e715-25f1-40bc-9444-32ebed1a23c1)
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/98d34391-8309-4787-aee1-43c1e9d5e995)
配置如图ccache: true始终无法编译通过，有时间请指点下是否配置有问题 谢谢

**Comment by dabao1955** [comment]
~~没遇到过诶~~
这看起来貌似不是ccache的问题诶

**Comment by dabao1955** [comment]
额为啥要禁用aosp-gcc

**Comment by Fyg369** [comment]
> 额为啥要禁用aosp-gcc

因为Enable ccache(Only valid when compiled with clang)所以关了，开启aosp-gcc是不是ccache就失效了

**Comment by dabao1955** [comment]
关于aosp-clang选项的描述(也适用于第三方clang):
"Use aosp-gcc to compile the kernel or assist in compiling the kernel (when aosp-clang is enabled)"
gcc只是起辅助编译作用(例如ld,as什么的)
```
if [ ${{ inputs.ccache }} = true ]; then
   export USE_CCACHE=1
   make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC="ccache clang" ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }}
```

**Comment by Fyg369** [comment]
> 关于aosp-clang选项的描述(也适用于第三方clang): "Use aosp-gcc to compile the kernel or assist in compiling the kernel (when aosp-clang is enabled)" gcc只是起辅助编译作用(例如ld,as什么的)
> 
> ```
> if [ ${{ inputs.ccache }} = true ]; then
>    export USE_CCACHE=1
>    make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC="ccache clang" ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }}
> ```

所以上图配置中在开启Gcc之后ccache就是有效的？

**Comment by dabao1955** [comment]
是这样的

**Comment by Fyg369** [comment]
> 是这样的

感谢回复

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/bffa9005-6680-4fb4-ac89-f9749667dbcd)
开启Kali-Nethunter支持大佬有时间可以参考下
https://github.com/Biohazardousrom/Kali-defconfig-checker

**Comment by dabao1955** [comment]
没看懂怎么用

**Comment by Fyg369** [comment]
> 没看懂怎么用

应该和开启lxc配置一样，只是开启支持Kali-Nethunter的配置，然后写入到源码defconfig文件里

**Comment by Fyg369** [comment]
再次打扰一下，不知道大佬有没有时间，能否添加一次同时编译多个内核源码？

**Comment by dabao1955** [comment]
> 再次打扰一下，不知道大佬有没有时间，能否添加一次同时编译多个内核源码？

虽然但是，可以配置多个工作流的说

**Comment by Fyg369** [comment]
> > 再次打扰一下，不知道大佬有没有时间，能否添加一次同时编译多个内核源码？
> 
> 虽然但是，可以配置多个工作流的说

确实可以配置多个工作流，但是每次更改一次配置或者改其它东西就会触发自动编译，这个能改成修改配置不会自动编译就好了，想编译的时候手动运行就行

**Comment by dabao1955** [comment]
建议查看一下wirkflow文件，我感觉跟action没太大关系。
例如:
```
on:
  push:
```
改成
```
on:
  workflow_dispatch:
```
