### ISSUE TITLE
[Bug]: The build process fails with a "can't open file" error for `drivers/kernelsu/Kconfig`.

### ISSUE THREAD

**Issue by WhiteSnow00** [dabao1955/kernel_build_action#40]
### CheckBox

- [X] I have searched the issue list and found no similar issues.
- [X] I use the official action instead of someone else's
- [X] I have read the FAQ section in README.md

### Configuration

# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/Shirayuki39/kernel_new
          kernel-dir: msm-5.10
          kernel-branch: shirayuki-5.10
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          anykernel3: true

### Describe the bug

drivers/Kconfig:240: can't open file "drivers/kernelsu/Kconfig"
make[3]: *** [../scripts/kconfig/Makefile:88: gki_defconfig] Error 1
make[2]: *** [../Makefile:618: gki_defconfig] Error 2
make[1]: *** [/home/runner/work/kernel_build_action/kernel_build_action/kernel/msm-5.10/Makefile:357: __build_one_by_one] Error 2
make[1]: Leaving directory '/home/runner/work/kernel_build_action/kernel_build_action/kernel/msm-5.10/out'
make: *** [Makefile:192: __sub-make] Error 2

**Comment by dabao1955** [comment]
Not enable ksu？

**Comment by Fyg369** [comment]
> Not enable ksu？

编译脚本里需要加个判断是否内核源码已存在ksu

**Comment by dabao1955** [comment]
> > Not enable ksu？
> 
> ksu判断代码可能需要在修改一下，编译脚本里可能需要加个判断，是否内核源码已存在kernelsu文件夹

Compiling with a script is not the same as compiling with a workflow.

**Comment by Fyg369** [comment]
> > > Not enable ksu？
> > 
> > 
> > ksu判断代码可能需要在修改一下，编译脚本里可能需要加个判断，是否内核源码已存在kernelsu文件夹
> 
> Compiling with a script is not the same as compiling with a workflow.

这里判断代码根据上面报错情况是否需要修改一下？
if [ ${{ inputs.ksu }} = true ]; then
            echo "::group:: Initializing KernelSU"
            if [ -f KernelSU/kernel/Kconfig ]; then
                echo "KernelSU has been initialized,skipped."

**Comment by dabao1955** [comment]
full changelog please

**Comment by Fyg369** [comment]
> full build log please

Building Kernel with selected cross compiler
  mkdir: created directory 'out'
  using command: make -j4 gki_defconfig ARCH=arm64 all  O=out PATH=/home/runner/clang/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CROSS_COMPILE=/home/runner/gcc-64/bin/aarch64-linux-android- CROSS_COMPILE_ARM32=/home/runner/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC=clang
  make[1]: Entering directory '/home/runner/work/Kernel-Action/Kernel-Action/kernel/vip/out'
    GEN     Makefile
    HOSTCC  scripts/basic/fixdep
    HOSTCC  scripts/kconfig/conf.o
    HOSTCC  scripts/kconfig/confdata.o
    HOSTCC  scripts/kconfig/expr.o
    LEX     scripts/kconfig/lexer.lex.c
    YACC    scripts/kconfig/parser.tab.[ch]
    HOSTCC  scripts/kconfig/preprocess.o
    HOSTCC  scripts/kconfig/symbol.o
    HOSTCC  scripts/kconfig/util.o
    HOSTCC  scripts/kconfig/lexer.lex.o
    HOSTCC  scripts/kconfig/parser.tab.o
    HOSTLD  scripts/kconfig/conf
  drivers/Kconfig:240: can't open file "drivers/kernelsu/Kconfig"
  make[3]: *** [../scripts/kconfig/Makefile:88: gki_defconfig] Error 1
  make[2]: *** [../Makefile:618: gki_defconfig] Error 2
  make[1]: *** [/home/runner/work/Kernel-Action/Kernel-Action/kernel/vip/Makefile:357: __build_one_by_one] Error 2
  make[1]: Leaving directory '/home/runner/work/Kernel-Action/Kernel-Action/kernel/vip/out'
  make: *** [Makefile:192: __sub-make] Error 2
  Error: Process completed with exit code 2.

**Comment by dabao1955** [comment]
No KernelSU directory in original kernel source code

**Comment by Fyg369** [comment]
> No KernelSU directory in original kernel source code

不用开启ksu选项
![Screenshot_20241111-140845](https://github.com/user-attachments/assets/f4aa4fa1-f3c8-4641-a430-acfc4412a625)

**Comment by averagePedestrian** [comment]
@dabao1955, I want to use a KSU fork, so if I set `ksu-other` to `true` do I need to set `ksu: true` too?

**Comment by Fyg369** [comment]
> @dabao1955, I want to use a KSU fork, so if I set `ksu-other` to `true` do I need to set `ksu: true` too?

ksu: true
ksu-version: main
ksu-other: true
ksu-url: https://github.com/rsuntk/KernelSU

**Comment by averagePedestrian** [comment]
> > @dabao1955, I want to use a KSU fork, so if I set `ksu-other` to `true` do I need to set `ksu: true` too?
> 
> ksu: true ksu-version: main ksu-other: true ksu-url: https://github.com/rsuntk/KernelSU

Didn't work it still cloned the original KSU repo

```
ksu: true
          ksu-version: legacy
          ksu-other: true
          ksu-url: https://github.com/backslashxx/KernelSU
```

```
[+] Setting up KernelSU...
  Cloning into 'KernelSU'...
  [+] Repository cloned.
  No local changes to save
  [-] Stashed current changes.
  Already up to date.
  [+] Repository updated.
  error: pathspec 'legacy' did not match any file(s) known to git
  [-] Checkout default branch
  [+] Symlink created.
  [+] Modified Makefile.
  [+] Modified Kconfig.
  [+] Done.
  ```

**Comment by Fyg369** [comment]
> > > @dabao1955, I want to use a KSU fork, so if I set `ksu-other` to `true` do I need to set `ksu: true` too?
> > 
> > 
> > ksu: true ksu-version: main ksu-other: true ksu-url: https://github.com/rsuntk/KernelSU
> 
> Didn't work it still cloned the original KSU repo
> 
> ```
> ksu: true
> ksu-version: legacy
> ksu-other: true
> ksu-url: https://github.com/backslashxx/KernelSU
> ```
> 
> ```
> [+] Setting up KernelSU...
>   Cloning into 'KernelSU'...
>   [+] Repository cloned.
>   No local changes to save
>   [-] Stashed current changes.
>   Already up to date.
>   [+] Repository updated.
>   error: pathspec 'legacy' did not match any file(s) known to git
>   [-] Checkout default branch
>   [+] Symlink created.
>   [+] Modified Makefile.
>   [+] Modified Kconfig.
>   [+] Done.
> ```

ksu-version: legacy

**Comment by dabao1955** [comment]
Well test workflow tested successfully...? I did not know if it is a bug or kernel source problem?
How about official KernelSU?

**Comment by Fyg369** [comment]
> Well test workflow tested successfully...? I did not know if it is a bug or kernel source problem? How about official KernelSU?

If there is no feedback, the problem should be solved hahaha

**Comment by averagePedestrian** [comment]
Apologies for the late reply, everyone. The issue was with the KSU fork.

**Comment by Fyg369** [comment]
if [ ${{ inputs.aosp-gcc }} = true ]; then
             if [ -d $HOME/clang ]; then
         if [ ! -z ${{ inputs.other-gcc64-url }} ] && [ ! -z ${{ inputs.other-gcc32-url }} ]; then
             echo "::group:: Downloading 3rd gcc"
             export OTHER_GCC64_URL=${{ inputs.other-gcc32-url }}
             export OTHER_GCC32_URL=${{ inputs.other-gcc64-url }}
             if [[ "$OTHER_GCC64_URL" == *'.tar.gz' ]]; then
                 mkdir $HOME/gcc-64 -p -v
                 aria2c -o gcc-aarch64.tar.gz "$OTHER_GCC64_URL"
                 tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
             elif [[ "$OTHER_GCC64_URL" == *'.zip' ]]; then
                 mkdir $HOME/gcc-64 -p -v
                 aria2c -o gcc-aarch64.zip "$OTHER_GCC64_URL" 
                 unzip -q gcc-aarch64.zip -d $HOME/gcc-64
             elif [[ "$OTHER_GCC64_URL" == *'.tar.xz' ]]; then
                 mkdir $HOME/gcc-64 -p -v
                 aria2c -o gcc-aarch64.tar.xz "$OTHER_GCC64_URL"         
                 tar -C $HOME/gcc-64 -xf gcc-aarch64.tar.xz
             else
                 git clone "$OTHER_GCC64_URL" $HOME/gcc-64 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc64-branch }}
             fi

             if [[ "$OTHER_GCC32_URL" == *'.tar.gz' ]]; then
                 mkdir $HOME/gcc-32 -p -v
                 aria2c -o gcc-arm.tar.gz "$OTHER_GCC32_URL"
                 tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
             elif [[ "$OTHER_GCC32_URL" == *'.zip' ]]; then
                 mkdir $HOME/gcc-32 -p -v
                 aria2c -o gcc-arm.zip "$OTHER_GCC32_URL" 
                 unzip -q gcc-arm.zip -d $HOME/gcc-32
             elif [[ "$OTHER_GCC32_URL" == *'.tar.xz' ]]; then
                 mkdir $HOME/gcc-32 -p -v
                 aria2c -o gcc-arm.tar.xz "$OTHER_GCC32_URL"         
                 tar -C $HOME/gcc-32 -xf gcc-arm.tar.xz
             else
                 git clone "$OTHER_GCC32_URL" $HOME/gcc-32 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc32-branch }}
             fi
           fi
         fi
         else
             echo "::group:: Downloading AOSP GCC"
             if [ -d $HOME/clang ]; then
                 mkdir -p -v $HOME/gcc-64
                 aria2c -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
                 tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
                 mkdir -p -v $HOME/gcc-32
                 aria2c -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
                 tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
             elif [ ${{ inputs.aosp-clang }} = true ] && [ ${{ inputs.android-ndk }} = true ]; then
                 echo "Error: The two options aosp-clang and android-ndk will conflict with each other, please turn off one." && exit 15
             else
                 git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-64
                 git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-32
             fi           
         fi
         if [ ! -d $HOME/gcc-64/bin/ ] || [ ! -d $HOME/gcc-32/bin/ ]; then
             [ ! -d $HOME/gcc-64/bin/ ] && mv $HOME/gcc-64/*/* $HOME/gcc-64/
             [ ! -d $HOME/gcc-32/bin/ ] && mv $HOME/gcc-32/*/* $HOME/gcc-32/
         fi
         echo "::endgroup::"

大佬请帮忙看下，下载第三方GCC还是AOSP GCC，上面这段代码好像没有执行下面这段代码
         if [ ! -d $HOME/gcc-64/bin/ ] || [ ! -d $HOME/gcc-32/bin/ ]; then
             [ ! -d $HOME/gcc-64/bin/ ] && mv $HOME/gcc-64/*/* $HOME/gcc-64/
             [ ! -d $HOME/gcc-32/bin/ ] && mv $HOME/gcc-32/*/* $HOME/gcc-32/
         fi

**Comment by Fyg369** [comment]
已添加第三方gcc下载代码，并且编译测试成功
无其它任何代码修改，只添加和修改代码如下:
  aosp-gcc:
    description: 'Use gcc from aosp project.'
    required: true
    default: true
  other-gcc32-url:
    required: false
    default: ''
  other-gcc32-branch:
    required: false
    default: main
  other-gcc64-url:
    required: false
    default: ''
  other-gcc64-branch:
    required: false
    default: main

         if [ ${{ inputs.aosp-gcc }} = true ]; then
             if [ -d $HOME/clang ]; then
         if [ ! -z ${{ inputs.other-gcc64-url }} ] && [ ! -z ${{ inputs.other-gcc32-url }} ]; then
             echo "::group:: Downloading 3rd gcc"
             export OTHER_GCC64_URL=${{ inputs.other-gcc64-url }}
             export OTHER_GCC32_URL=${{ inputs.other-gcc32-url }}
             if [[ "$OTHER_GCC64_URL" == *'.tar.gz' ]]; then
                 mkdir -p -v $HOME/gcc-64
                 aria2c -o gcc-aarch64.tar.gz "$OTHER_GCC64_URL"
                 tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
             elif [[ "$OTHER_GCC64_URL" == *'.zip' ]]; then
                 mkdir -p -v $HOME/gcc-64
                 aria2c -o gcc-aarch64.zip "$OTHER_GCC64_URL" 
                 unzip -q gcc-aarch64.zip -d $HOME/gcc-64
             elif [[ "$OTHER_GCC64_URL" == *'.tar.xz' ]]; then
                 mkdir -p -v $HOME/gcc-64
                 aria2c -o gcc-aarch64.tar.xz "$OTHER_GCC64_URL"         
                 tar -C $HOME/gcc-64 -xf gcc-aarch64.tar.xz
             else
                 git clone "$OTHER_GCC64_URL" $HOME/gcc-64 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc64-branch }}
             fi

             if [[ "$OTHER_GCC32_URL" == *'.tar.gz' ]]; then
                 mkdir -p -v $HOME/gcc-32
                 aria2c -o gcc-arm.tar.gz "$OTHER_GCC32_URL"
                 tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
             elif [[ "$OTHER_GCC32_URL" == *'.zip' ]]; then
                 mkdir -p -v $HOME/gcc-32
                 aria2c -o gcc-arm.zip "$OTHER_GCC32_URL" 
                 unzip -q gcc-arm.zip -d $HOME/gcc-32
             elif [[ "$OTHER_GCC32_URL" == *'.tar.xz' ]]; then
                 mkdir -p -v $HOME/gcc-32
                 aria2c -o gcc-arm.tar.xz "$OTHER_GCC32_URL"         
                 tar -C $HOME/gcc-32 -xf gcc-arm.tar.xz
             else
                 git clone "$OTHER_GCC32_URL" $HOME/gcc-32 --depth=${{ inputs.depth }} -b ${{ inputs.other-gcc32-branch }}       
         fi
         else
             echo "::group:: Downloading AOSP GCC"
             if [ -d $HOME/clang ]; then
                 mkdir -p -v $HOME/gcc-64
                 aria2c -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
                 tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
                 mkdir -p -v $HOME/gcc-32
                 aria2c -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
                 tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
             elif [ ${{ inputs.aosp-clang }} = true ] && [ ${{ inputs.android-ndk }} = true ]; then
                 echo "Error: The two options aosp-clang and android-ndk will conflict with each other, please turn off one." && exit 15
             else
                 git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-64
                 git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-32
             fi
           fi 
         fi
         if [ ! -d $HOME/gcc-64/bin/ ] || [ ! -d $HOME/gcc-32/bin/ ]; then
             [ ! -d $HOME/gcc-64/bin/ ] && mv $HOME/gcc-64/*/* $HOME/gcc-64/
             [ ! -d $HOME/gcc-32/bin/ ] && mv $HOME/gcc-32/*/* $HOME/gcc-32/
             fi 
         fi
         echo "::endgroup::"

**Comment by dabao1955** [comment]
So？

**Comment by Fyg369** [comment]
> 所以？



> So？

没有电脑如何提交pr？

**Comment by dabao1955** [comment]
> > 所以？
> 
> > So？
> 
> 没有电脑如何提交pr？

请不要发送无关评论谢谢
