### ISSUE TITLE
[common]: Preserve Previously Released Assets in GitHub Release Section

### ISSUE THREAD

**Issue by averagePedestrian** [dabao1955/kernel_build_action#42]
### Describe the problem

After each successful kernel compilation, the previous release asset is deleted before the new one is uploaded to the GitHub release section. This causes a loss of historical release assets. Is there a way to modify this behaviour to keep all previously released assets available in the release section?
![12-November-2024 @ 11 47 26 AM (msedge)](https://github.com/user-attachments/assets/688f5eeb-79fc-455a-b16e-659fb18d24cd)

**Comment by dabao1955** [comment]
try 7255d98
