### ISSUE TITLE
kali nethunter support

### ISSUE THREAD

**Issue by dabao1955** [dabao1955/kernel_build_action#5]
@Fyg369

try:
```
      - name: Build
        uses: dabao1955/kernel_build_action@a0e78d5f540cb8a0d8a1f7c482e6ac6280e06147
        
```
N: This is a experimental function

**Comment by Fyg369** [comment]
![Screenshot_20231219-231944](https://github.com/dabao1955/kernel_build_action/assets/142138034/b4a85633-cfa9-4475-80d1-eb683f5211a3)
![Screenshot_20231219-233456](https://github.com/dabao1955/kernel_build_action/assets/142138034/d4155aa4-a8f2-4184-a580-16c465b9c6d2)
虽然编译成功了，但总感觉乖乖的，好像没成功一样  哈哈

**Comment by Fyg369** [comment]
![Screenshot_20231219-234126](https://github.com/dabao1955/kernel_build_action/assets/142138034/4c92b71f-06f2-4f9e-af8d-7fcfb4c389cd)

**Comment by dabao1955** [comment]
绷，一看才发现少写个t

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/ff3bea0e-4edf-4683-ba54-299614ec3de6)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/9dbd1e7a-39a0-4c0d-ac7a-75443254e88d)
我添加了如上图代码，不知道位置对不对，运行时会不会生效，大佬有时间给指点下 谢谢

**Comment by Fyg369** [comment]
![1](https://github.com/dabao1955/kernel_build_action/assets/142138034/f9fcc24d-09d2-4635-897e-b1a2ca77ea2a)
![3](https://github.com/dabao1955/kernel_build_action/assets/142138034/de3ff413-84f3-42a5-88f3-78bd8b2cc8c0)
![2](https://github.com/dabao1955/kernel_build_action/assets/142138034/8fac25f3-8e53-47ce-9160-e1bab5c96050)
add-rtl88xxau-5.6.4.2-drivers.patch
add-wifi-injection-4.14.patch
这两个补丁我在虚拟机里都可以成功编译，添加的也没毛病啊！搞不懂为啥会出现如上图的问题

**Comment by SekaiMoe** [comment]
> ![1](https://private-user-images.githubusercontent.com/142138034/291792410-f9fcc24d-09d2-4635-897e-b1a2ca77ea2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTk5MDcsIm5iZiI6MTcwMzA1OTYwNywicGF0aCI6Ii8xNDIxMzgwMzQvMjkxNzkyNDEwLWY5ZmNjMjRkLTA5ZDItNDYzNS04OTdlLWIxYTJjYTc3ZWEyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwODA2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzMwY2UyN2Y5YTA0MTE2MmI4YWVlZWRmNmQxY2E2YThlZmQzZmM5MmRkZjVjOWY0MzI4Njk3Y2VhMTNiMTgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OjUrLjcR0ikVfNgnOqdoPb59Os1uafB2VfUfdGFZSck) ![3](https://private-user-images.githubusercontent.com/142138034/291792427-de3ff413-84f3-42a5-88f3-78bd8b2cc8c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTk5MDcsIm5iZiI6MTcwMzA1OTYwNywicGF0aCI6Ii8xNDIxMzgwMzQvMjkxNzkyNDI3LWRlM2ZmNDEzLTg0ZjMtNDJhNS04OGYzLTc4YmQ4YjJjYzhjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwODA2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGYyNzQ3ZjE5OTY5ZjgyMjU2NmVlNTFiNmE5NWM1ODU0ZGM0OTY4MGE4ZDBiNzZjNDY0NDRlOTdjNzdlZGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-QMzhKgeY1_kBpcW_j-0e4FQf2kq9wVmIpqx4tEKDI4) ![2](https://private-user-images.githubusercontent.com/142138034/291792446-8fac25f3-8e53-47ce-9160-e1bab5c96050.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTk5MDcsIm5iZiI6MTcwMzA1OTYwNywicGF0aCI6Ii8xNDIxMzgwMzQvMjkxNzkyNDQ2LThmYWMyNWYzLThlNTMtNDdjZS05MTYwLWUxYmFiNWM5NjA1MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwODA2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDc4MDRjNmRlZGZmNTIyNWQyZWU2ZDUzNjc1ZTJmY2ViMmQ2ODE5MWE4ZTJkMGJhMTJjOTFmMmMwNzQzNzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mj9Hv4-5CggGPnGZmsQIQnkISXh_mqe8ldKjhbmp7kk) add-rtl88xxau-5.6.4.2-drivers.patch add-wifi-injection-4.14.patch 这两个补丁我在虚拟机里都可以成功编译，添加的也没毛病啊！搞不懂为啥会出现如上图的问题

？

**Comment by SekaiMoe** [comment]
@Fyg369 看一下这样有用没

https://github.com/SekaiMoe/Kernel-Action/commit/be3d6dbe6301bea0f5a36a075880bddd36955a0b

**Comment by SekaiMoe** [comment]
> @Fyg369 看一下这样有用没
> 
> [SekaiMoe/Kernel-Action@be3d6db](https://github.com/SekaiMoe/Kernel-Action/commit/be3d6dbe6301bea0f5a36a075880bddd36955a0b)

绷不住了，改了也没用

**Comment by Fyg369** [comment]
> > @Fyg369 看一下这样有用没
> > [SekaiMoe/Kernel-Action@be3d6db](https://github.com/SekaiMoe/Kernel-Action/commit/be3d6dbe6301bea0f5a36a075880bddd36955a0b)
> 
> ~绷不住了，改了也没用~ 哦原来是workflow没改 改完了就好了 https://github.com/SekaiMoe/Kernel-Action/actions/runs/7273778239/job/19818428373

非常感谢修复，已经成功编译了，顺便请教下是什么原因导致的呢

**Comment by dabao1955** [comment]
不道，应该是少个fi导致的

**Comment by Fyg369** [comment]
> 不道，应该是少个fi导致的

![69](https://github.com/dabao1955/kernel_build_action/assets/142138034/3ff71b46-c308-4a20-ae61-055c1625a5fc)
![96](https://github.com/dabao1955/kernel_build_action/assets/142138034/5e58276f-4c91-4c91-b8a1-b7edbc474959)
对比下代码因该不单单是少个fi导致的  哈哈哈

**Comment by dabao1955** [comment]
但是看起来确实是这样，去掉这些仅仅是为了方便调试

**Comment by Fyg369** [comment]
> 但是看起来确实是这样，去掉这些仅仅是为了方便调试

![Screenshot_20231220-233846](https://github.com/dabao1955/kernel_build_action/assets/142138034/4c69f4e1-1395-464e-ba2e-4c580d16327f)
![Screenshot_20231220-233803](https://github.com/dabao1955/kernel_build_action/assets/142138034/ef77f8f8-18d0-4f35-ad7a-87618da88aff)
v3打包没问题，v4打包就出现了如上问题

**Comment by dabao1955** [comment]
https://github.com/actions/upload-artifact/issues/487

**Comment by Fyg369** [comment]
> [actions/upload-artifact#487](https://github.com/actions/upload-artifact/issues/487)

好的

**Comment by Fyg369** [comment]
更新了最新1.5.5出现了如下图问题，是编译工具的问题吗？
![Screenshot_20240208-113048](https://github.com/dabao1955/kernel_build_action/assets/142138034/8a5c30c4-8b84-41a0-9a59-f855c3622fb0)

**Comment by Fyg369** [comment]
我改了下编译工具下载路径成功编译
![Screenshot_20240208-125029](https://github.com/dabao1955/kernel_build_action/assets/142138034/c575de3e-b6a0-4af1-80bd-6f20d6ed605d)

**Comment by dabao1955** [comment]
> 更新了最新1.5.5出现了如下图问题，是编译工具的问题吗？ ![Screenshot_20240208-113048](https://private-user-images.githubusercontent.com/142138034/303205028-8a5c30c4-8b84-41a0-9a59-f855c3622fb0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTMwNzAsIm5iZiI6MTcwNzM5Mjc3MCwicGF0aCI6Ii8xNDIxMzgwMzQvMzAzMjA1MDI4LThhNWMzMGM0LThiODQtNDFhMC05YTU5LWY4NTVjMzYyMmZiMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMTQ2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzQ5NWM0OTc5YzdlOWZmMGVjNWVmYjg1ZDFmNzFiZWE0ZGRlZjA5NzU0MzA3MjMwNjNiNjNmMTk3ZTRkZDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U_8dUMqFyqKu7FLLVjqdt0MU3NJ4njPOgXBXMOUm-5A)

7c171b3 已修复
