### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by whyakari** [dabao1955/kernel_build_action#6]
config parameter it does not work with kernel that has defconfig in vendor arch/arm64/configs/`vendor`/defconfig

**Comment by dabao1955** [comment]
> config parameter it does not work with kernel that has defconfig in vendor arch/arm64/configs/`vendor`/defconfig

try(for example):
```
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_xiaomi_
          branch: lineage-20
          config: vendor/xiaomi/cas_defconfig

**Comment by dabao1955** [comment]
Sorry to bother you again.

I don't quite understand whether you are referring to `vendor/xxx_defconfig` or `vendor/xxx.config`.
If it's the former, I've given examples for reference.
If it's the latter, commit 13a7172 may have fixed the issue.
