### ISSUE TITLE
第三方编译器[Bug]: 

### ISSUE THREAD

**Issue by Fyg369** [dabao1955/kernel_build_action#8]
### CheckBox

- [X] I have searched the issue list and found no similar issues.
- [X] I use the official action instead of someone else's

### Configuration

uses: dabao1955/kernel_build_action@main
with:
  xxx: xxx

### Describe the bug

Warning: Unexpected input(s) 'other-clang', valid inputs are ['kernel-url', 'depth', 'vendor-url', 'kernel-dir', 'vendor', 'vendor-dir', 'branch', 'config', 'arch', 'android-version', 'apatch', 'ksu', 'ksu-version', 'kprobes', 'overlayfs', 'disable_fst', 'disable_cc_werror', 'disable-lto', 'lxc', 'lxc-patch', 'nethunter', 'nethunter-patch', 'bbrplus', 'kvm', 'ccache', 'aosp-gcc', 'aosp-clang', 'aosp-clang-version', 'other-clang-url', 'other-clang-branch', 'android-ndk', 'android-ndk-version', 'python-27', 'anykernel3', 'bootimg-url', 'release', 'access-token', 'extra-cmd']

### Screenshots

![Screenshot_20240309-195028](https://github.com/dabao1955/kernel_build_action/assets/142138034/f6b40110-6f2a-4c56-88fb-e2292b5dc79a)
![Screenshot_20240309-195058](https://github.com/dabao1955/kernel_build_action/assets/142138034/95ad8a8b-0f6a-4a81-b938-7cd3dd89193c)

**Comment by dabao1955** [comment]
see 

https://github.com/dabao1955/kernel_build_action?tab=readme-ov-file#how-to-use-3rd-clang

**Comment by Fyg369** [comment]
![Screenshot_20240310-074815](https://github.com/dabao1955/kernel_build_action/assets/142138034/fe44a43b-49cf-437d-a494-eb29221cbbe9)
![Screenshot_20240310-074718](https://github.com/dabao1955/kernel_build_action/assets/142138034/70bfe63f-8e05-4c6e-966d-b49783bd3f10)
不知是否399行这里导致我编译出现的警告问题？

**Comment by Fyg369** [comment]
![555](https://github.com/dabao1955/kernel_build_action/assets/142138034/8e84aa6f-b363-4228-b555-b288a0d0a35d)
![666](https://github.com/dabao1955/kernel_build_action/assets/142138034/aa9f7679-ef3b-431d-857e-4df3c9071fcc)
只要把设置成aosp-clang: false就会出现上面报错，设置成aosp-clang: true就可以编译成功
